# Generated by Django 4.2.5 on 2023-10-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='forecast',
            field=models.JSONField(default=dict),
        ),
    ]
