# Generated by Django 4.2.5 on 2023-10-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categories',
            unique_together=set(),
        ),
    ]
