# Generated by Django 4.2.5 on 2023-09-24 12:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='День продаж')),
                ('sales_units', models.IntegerField(db_index=True, verbose_name='Число проданных товаров без признака промо')),
                ('sales_units_promo', models.IntegerField(db_index=True, verbose_name='Число проданных товаров c признаком промо')),
                ('sales_rub', models.FloatField(db_index=True, verbose_name='Продажи без признака промо в РУБ')),
                ('subcatesales_run_promgory', models.FloatField(db_index=True, verbose_name='Продажи с признаком промо в РУБ')),
            ],
        ),
        migrations.CreateModel(
            name='SalesUnitsForForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Прогнозируемый день продаж')),
                ('quantity', models.IntegerField(db_index=True, verbose_name='Прогнозируемое число продаж')),
            ],
        ),
        migrations.RemoveField(
            model_name='sales',
            name='data',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='pr_promo_sales_in_rub',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='pr_promo_sales_in_units',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='pr_sales_in_rub',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='pr_sales_in_units',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='pr_sales_type',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='pr_sku',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='st',
        ),
        migrations.AddField(
            model_name='categories',
            name='category',
            field=models.TextField(db_index=True, default=django.utils.timezone.now, unique=True, verbose_name='Категория товаров'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='group',
            field=models.TextField(db_index=True, default=django.utils.timezone.now, unique=True, verbose_name='Группа товаров'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='sku',
            field=models.TextField(db_index=True, default=django.utils.timezone.now, unique=True, verbose_name='Артикул'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='subcategory',
            field=models.TextField(db_index=True, default=django.utils.timezone.now, unique=True, verbose_name='Подкатегория товаров'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='uom',
            field=models.IntegerField(default=1, verbose_name='Единица измерения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecast',
            name='forecast_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата прогноза'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecast',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.shops', verbose_name='Магаизн'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='sku',
            field=models.TextField(db_index=True, default=1, unique=True, verbose_name='Артикул'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.shops', verbose_name='Магаизн'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shops',
            name='city',
            field=models.TextField(db_index=True, default=1, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shops',
            name='division',
            field=models.TextField(db_index=True, default=1, verbose_name='Подразделение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shops',
            name='is_active',
            field=models.BooleanField(db_index=True, default=1, verbose_name='Статус магазина(открыт/закрыт)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shops',
            name='loc',
            field=models.IntegerField(db_index=True, default=1, verbose_name='Локация магазина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shops',
            name='size',
            field=models.IntegerField(db_index=True, default=1, verbose_name='Тип размера магазина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shops',
            name='store',
            field=models.TextField(db_index=True, default=1, unique=True, verbose_name='Магаизн'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shops',
            name='type_format',
            field=models.IntegerField(db_index=True, default=1, verbose_name='Формата магазина'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ForecastInStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.TextField(db_index=True, unique=True, verbose_name='Артикул')),
                ('sales_units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.salesunitsforforecast', verbose_name='Прогноз числа проданных товаров без признака промо')),
            ],
        ),
        migrations.AddField(
            model_name='forecast',
            name='forecast',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.forecastinstore', verbose_name='Прогноз'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='fact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.salesinstore', verbose_name='Продажи'),
            preserve_default=False,
        ),
    ]
