# Generated by Django 4.2.5 on 2023-10-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='product',
            new_name='product_name',
        ),
    ]
