# Generated by Django 4.2.5 on 2023-09-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stores',
            name='division',
            field=models.CharField(max_length=32, verbose_name='Подразделение'),
        ),
    ]
