# Generated by Django 4.2.5 on 2023-10-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_sales_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sales',
            unique_together={('product_name', 'store')},
        ),
    ]
