version: '3.8'

services:


  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/

    depends_on:
      - backend

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:8000"
    volumes:
      - ../frontend/:/app/result_build/
      - static_value:/var/html/static/
      - media_value:/var/html/media/

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build:
      context: ../backend
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    links:
      - redis
    depends_on:
      - redis

volumes:
  static_value:
  media_value:



