version: '3.8'

services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:8000"
    volumes:
      - ../frontend/:/app/result_build/
      - static_value:/var/html/static/
      - media_value:/var/html/media/

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - ./.env

  nginx:
    image: nginx:1.25.2-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/

    depends_on:
      - backend

volumes:
  static_value:
  media_value:



